name: Terraform

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "lab-17/fullstack-app/infrastructure/terraform/**"

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lab-17/fullstack-app/infrastructure/terraform
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -check
      - run: terraform init
        env:
          YC_TOKEN: ${{ secrets.YC_TOKEN }}
          YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
          YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
      - run: terraform validate

